### ISSUE TITLE
MacOS implementation

### ISSUE THREAD

**Issue by SergeShkurko** [auth0/auth0-flutter#323]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

App crushed when i run it on macOS

### Describe the ideal solution

Auth0 cocoapods package supports macOS platform. Will need only expose it availability

### Additional context

I made simple implementation. But i did't reuse code. I did copy some ios code to macos folder and made small fixes for availability to work

in next time will need compose ios / macos in one folder & will use conditions in swift / objc like this:
```
#if os(iOS)
import Flutter
import UIKit
#elseif os(macOS)
import Cocoa
import FlutterMacOS
#endif
import CoreGraphics

``` 

[SergeShkurko:feature/macos_support](https://github.com/SergeShkurko/auth0-flutter/tree/feature/macos_support)

```
# set `platform :osx, '11.0'` here `macos/Podfile`

# setup build target version to `11.0` anywhere in projec. Will need:
# edit `xcode->Project Runner->Build Settings-> MACOSX_DEPLOYMENT_TARGET==11.0`
# then `xcode->Targets Runner->Build Settings-> MACOSX_DEPLOYMENT_TARGET==11.0`

# add to pubspec.yaml
dependency_overrides:
  auth0_flutter:
    git:
      url: https://github.com/SergeShkurko/auth0-flutter.git
      ref: feature/macos_support
      path: auth0_flutter
```
